apiVersion: apps/v1
kind: Deployment
metadata:
  name: super-mario-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: super-mario
  template:
    metadata:
      labels:
        app: super-mario
    spec:
      containers:
        - name: mario
          image: vks0012/mario:latest
          ports:
            - containerPort: 8080


---

apiVersion: v1
kind: Service 
metadata:
  name: super-mario-service
spec:
  selector:
    app: super-mario
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  
  type: LoadBalancer
  