name: Build Docker Image
# on:
#   push:
#     branches:
#       - main
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3


      - name: Dockerhub Login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin


      - name: Build and Push Docker Image to Dockerhub
        uses: docker/build-push-action@v2
        
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: | 
            vks0012/mario:${{ github.run_number }}
            vks0012/mario:latest

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: vks0012/mario:${{ github.run_number }}
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      
          