name: Build Docker Image
on:
  push:
    branches:
      - main
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Read and Bump Version
        id: version
        run: |
          version=$(cat .\version.txt)
          next_version=$((version + 1))
          echo "VERSION=$next_version" >> $GITHUB_ENV
          echo "$next_version" > version.txt

      - name: Dockerhub Login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin


      - name: Build and Push Docker Image to Dockerhub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: vks0012/mario:${{ env.VERSION }}