name: Build Docker Image
on:
  push:
    branches:
      - main
env:
  VERSION: $(( $(cat version.txt) + 1 ))
  TAG: $((VERSION + 1))
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3


      - name: Dockerhub Login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin


      - name: Build and Push Docker Image to Dockerhub
        uses: docker/build-push-action@v2
        
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: vks0012/mario:${{ env.TAG  }}